name: fakestore
description: "A new Flutter E-commerce (BLoC) project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # additional packages
  intl: ^0.19.0
  http: ^1.2.2
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  pinput: ^5.0.0
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  get_it: ^8.0.0

  # for bloc state manager
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #Local database
  flutter_secure_storage: ^9.2.2
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

  # Firebase pakeges
  # firebase_core: ^3.8.0
  # cloud_firestore: ^5.5.0
  # firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  drift_dev: ^2.23.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/screenshots/